name:                assimp
version:             0.0.0
github:              "joelburget/assimp"
license:             BSD3
author:              "Joel Burget"
maintainer:          "joelburget@gmail.com"
copyright:           "Joel Burget 2011-2012"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            media

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:          "/Important/: Install with
    @cabal install --extra-include-dirs \/usr\/local\/include\/assimp\/@
    Of course use the location of the include files on your system.
    .
    This library provides FFI bindings to the Assimp asset import
    library. It requires Assimp to already be installed. For more
    information about Assimp see the assimp website at
    <http://assimp.sourceforge.net/>.
    .
    This release corresponds to Assimp 2.0. When this package stabilizes I
    intend to track new releases of Assimp by also releasing new versions with
    the same version number, but this should be considered a beta release.
    Importing models is currently working. Textures and animations are
    untested.
    .
    Here is a sample program that imports a scene and then outputs the
    information contained in it.
    .
    > module Main where
    >
    > import System.Environment (getArgs)
    > import Graphics.Formats.Assimp
    >
    > -- Defines the preprocessing we want assimp to perform
    > processing = [ CalcTangentSpace
    >              , Triangulate
    >              , JoinIdenticalVertices
    >              , SortByPType
    >              ]
    >
    > main = do
    >   args <- getArgs
    >   mapM_ (print =<<)
    >     [ importFile (head args) processing -- Outputs all information in the scene
    >     , getVersionMajor     -- Print the major version of assimp
    >     , getVersionMinor     -- Print the minor version of assimp
    >     , getVersionRevision  -- Print the version revision of assimp
    >     ]
    .
    See <https://github.com/joelburget/Cologne/blob/master/Cologne/AssimpImport.hs>
    for more."


dependencies:
 - base         >= 4     && < 5
 - linear

ghc-options:
- -Wall

library:
  ghc-options:
  - -O1
  build-tools: hsc2hs
  extra-libraries: assimp
  include-dirs:
  - include
  - Graphics/Formats/
  source-dirs : .

executables:
  assimp-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - assimp